// ── Extra command databases (Git, Terraform, kubectl, npm, systemctl, jq, openssl, docker-compose)
// Merged into COMMANDS at runtime by app.js

const EXTRA_COMMANDS = {

  // ── GIT ──────────────────────────────────────────────────────────────────
  git: {
    tool: "git",
    description: "Distributed version control system",
    args: { description: "Git subcommand (commit, push, pull, clone, etc.)" },
    flags: {
      "commit":      "Record staged changes as a new snapshot in history",
      "push":        "Upload local commits to a remote repository",
      "pull":        "Fetch from remote and merge into current branch",
      "fetch":       "Download remote changes without merging",
      "clone":       "Clone a remote repository into a new directory",
      "checkout":    "Switch branches or restore working tree files",
      "switch":      "Switch branches (modern replacement for checkout -b)",
      "branch":      "List, create, or delete branches",
      "merge":       "Join two or more development histories together",
      "rebase":      "Reapply commits on top of another base tip",
      "stash":       "Temporarily shelve local changes",
      "status":      "Show the working tree status",
      "log":         "Show commit logs",
      "diff":        "Show changes between commits or working tree",
      "add":         "Stage file changes for the next commit",
      "reset":       "Unstage or undo commits",
      "revert":      "Create a new commit that undoes a previous commit",
      "tag":         "Create, list, or delete tags",
      "cherry-pick": "Apply the changes from a specific commit",
      "bisect":      "Binary search through history to find a bad commit",
      "remote":      "Manage connections to remote repositories",
      "init":        "Initialise a new empty Git repository",
      "rm":          "Remove files from the working tree and index",
      "show":        "Show a Git object (commit, tag, tree, blob)",
      "-m":          "Commit message (used with commit)",
      "-a":          "Automatically stage all tracked modified files",
      "-b":          "Create and switch to a new branch",
      "--amend":     "Modify the most recent commit (message or content)",
      "--rebase":    "Rebase instead of merge when pulling",
      "--force":     "Force push, overwriting remote history (use carefully!)",
      "--hard":      "Reset index and working tree (all local changes lost)",
      "--soft":      "Reset HEAD only, keep staged changes",
      "--mixed":     "Reset HEAD and index, keep working tree (default)",
      "--no-ff":     "Create a merge commit even for fast-forward merges",
      "--squash":    "Squash all commits into one before merging",
      "--oneline":   "Show each commit as a single line",
      "--graph":     "Draw an ASCII graph of the branch and merge history",
      "--all":       "Show logs/branches for all refs",
      "--cached":    "Compare staged changes (diff/reset)",
      "--stat":      "Show stats (files changed, insertions, deletions)",
      "-p":          "Show patch (diff) output",
      "-u":          "Set upstream tracking branch (push -u origin main)",
      "--tags":      "Fetch or push all tags",
      "--depth":     "Shallow clone with specified commit depth",
      "-i":          "Interactive mode (rebase -i, stash -i)",
      "--continue":  "Continue after resolving conflicts (rebase, cherry-pick)",
      "--abort":     "Abort the current in-progress operation",
      "config":      "Get or set repository or global configuration values",
      "clean":       "Remove untracked files from the working tree",
      "reflog":      "Show a log of all HEAD movements — essential for recovery",
      "worktree":    "Manage multiple working trees from one repository",
      "submodule":   "Manage submodules embedded in the repository",
      "shortlog":    "Summarise git log output grouped by author",
      "archive":     "Export a tree or commit as a tar/zip archive",
      "blame":       "Show which commit last modified each line of a file",
      "-D":          "Force-delete a branch even if not fully merged",
      "-f":          "Force — overwrite branch tip or overwrite ref",
      "--force-with-lease": "Safer force push — fails if remote has new commits you haven't fetched",
      "--no-verify": "Skip pre-commit and commit-msg hooks",
      "--fixup":     "Create a fixup! commit to be squashed by rebase --autosquash",
      "--autosquash":"Automatically squash fixup!/squash! commits during rebase -i",
      "--porcelain": "Machine-readable output format for scripting",
      "--short":     "Short format status output",
      "--global":    "Apply config to the global (~/.gitconfig) scope",
      "--local":     "Apply config to the repository (.git/config) scope",
      "--list":      "List all configuration variables",
      "-fd":         "Force-delete a branch (shorthand combination)"
    }
  },

  // ── TERRAFORM ────────────────────────────────────────────────────────────
  terraform: {
    tool: "terraform",
    description: "Infrastructure as Code tool by HashiCorp",
    args: { description: "Terraform subcommand (init, plan, apply, destroy, etc.)" },
    flags: {
      "init":        "Initialise a Terraform working directory (downloads providers)",
      "plan":        "Preview changes Terraform will make to infrastructure",
      "apply":       "Apply the planned changes to real infrastructure",
      "destroy":     "Destroy all resources managed by Terraform",
      "validate":    "Validate configuration files for syntax errors",
      "fmt":         "Reformat configuration files to canonical style",
      "output":      "Show output values from the state",
      "state":       "Advanced state management subcommand",
      "import":      "Import existing infrastructure into Terraform state",
      "taint":       "Mark a resource as tainted, forcing recreation on next apply",
      "untaint":     "Remove the tainted state from a resource",
      "workspace":   "Manage multiple state workspaces",
      "providers":   "Show required providers and their versions",
      "refresh":     "Update state to match real infrastructure",
      "graph":       "Output dependency graph in DOT format",
      "show":        "Show the current state or a plan file",
      "force-unlock":"Release a stuck state lock",
      "-auto-approve":   "Skip interactive approval prompt on apply/destroy",
      "-var":            "Set a single input variable value (-var 'key=value')",
      "-var-file":       "Load variable values from a .tfvars file",
      "-out":            "Save plan to a file for later apply",
      "-target":         "Focus apply/plan on a specific resource",
      "-parallelism":    "Limit number of concurrent operations (default: 10)",
      "-refresh=false":  "Skip refreshing state before plan/apply",
      "-reconfigure":    "Reconfigure the backend, ignoring any saved config",
      "-upgrade":        "Upgrade provider plugins to newest acceptable version",
      "-compact-warnings":"Show warnings in a more compact format",
      "-json":           "Output in machine-readable JSON format",
      "-lock=false":     "Disable state locking (use with caution)",
      "-lock-timeout":   "Duration to retry acquiring state lock",
      "-input=false":    "Disable interactive prompts",
      "-no-color":       "Disable color in output"
    }
  },

  // ── KUBECTL ──────────────────────────────────────────────────────────────
  kubectl: {
    tool: "kubernetes",
    description: "Kubernetes command-line tool — control clusters",
    args: { description: "kubectl subcommand (get, apply, describe, delete, etc.)" },
    flags: {
      "get":           "Display one or many resources",
      "apply":         "Apply a configuration to a resource from a file or stdin",
      "delete":        "Delete resources by filenames, resource names, or labels",
      "describe":      "Show detailed state of one or more resources",
      "create":        "Create a resource from a file or stdin",
      "edit":          "Edit a resource in the default editor",
      "exec":          "Execute a command inside a running container",
      "logs":          "Print logs from a container in a pod",
      "port-forward":  "Forward local port(s) to a pod",
      "scale":         "Scale a Deployment, ReplicaSet, or StatefulSet",
      "rollout":       "Manage rollouts (status, history, undo, restart)",
      "patch":         "Update fields of a resource using JSON/YAML patch",
      "label":         "Add or update labels on a resource",
      "annotate":      "Add or update annotations on a resource",
      "expose":        "Expose a resource as a new Kubernetes service",
      "run":           "Run a particular image in the cluster",
      "cp":            "Copy files between a container and local filesystem",
      "top":           "Show CPU and memory usage of nodes or pods",
      "config":        "Modify kubeconfig (current context, clusters, users)",
      "cluster-info":  "Display cluster endpoint information",
      "drain":         "Safely evict all pods from a node for maintenance",
      "cordon":        "Mark a node as unschedulable",
      "uncordon":      "Mark a node as schedulable",
      "taint":         "Update taints on one or more nodes",
      "-n":            "Namespace to operate in",
      "--namespace":   "Namespace to operate in (long form)",
      "-o":            "Output format: wide, json, yaml, jsonpath, custom-columns",
      "-f":            "Filename, directory, or URL of manifest file",
      "-l":            "Label selector to filter resources",
      "--all-namespaces":"List resources across all namespaces",
      "--dry-run":     "Preview changes without applying (client or server)",
      "--force":       "Immediately remove resources without graceful deletion",
      "--grace-period":"Period in seconds before forceful termination",
      "--watch":       "Watch for changes to the listed resources",
      "-it":           "Interactive terminal for exec",
      "--tail":        "Number of lines of log output to show",
      "--since":       "Show logs since this duration (e.g., 5m, 1h)",
      "--previous":    "Print logs from previous container instance",
      "--record":      "Record current command in the resource annotation",
      "--context":     "The kubeconfig context to use",
      "--kubeconfig":  "Path to the kubeconfig file",
      "-A":            "Shorthand for --all-namespaces",
      "wait":          "Wait until a specific condition is met on a resource",
      "api-resources": "List all supported API resource types in the cluster",
      "api-versions":  "List all supported API versions in the cluster",
      "explain":       "Show documentation for a resource field (e.g., kubectl explain pod.spec)",
      "proxy":         "Run a proxy to the Kubernetes API server on localhost",
      "certificate":   "Approve or deny pending certificate signing requests",
      "auth":          "Inspect or reconcile RBAC authorisation",
      "--server-side": "Perform server-side apply (more powerful conflict detection)",
      "--prune":       "Automatically delete resources missing from the applied manifests",
      "--cascade":     "Control cascade deletion of dependent resources (background/foreground/orphan)",
      "--for":         "Condition to wait for with kubectl wait (e.g., --for=condition=Ready)",
      "--timeout":     "Maximum time to wait before giving up (e.g., --timeout=60s)",
      "--output":      "Same as -o: control output format (json, yaml, wide, name, jsonpath…)",
      "--selector":    "Same as -l: filter resources by label selector",
      "--show-labels": "Show all labels as the last column in output",
      "--sort-by":     "Sort list results by a JSONPath expression",
      "--field-selector": "Filter resources by field value (e.g., status.phase=Running)"
    }
  },

  // ── NPM ──────────────────────────────────────────────────────────────────
  npm: {
    tool: "npm",
    description: "Node Package Manager — manage JavaScript dependencies",
    args: { description: "npm subcommand (install, run, build, publish, etc.)" },
    flags: {
      "install":       "Install all dependencies listed in package.json",
      "i":             "Alias for install",
      "uninstall":     "Remove a package from node_modules and package.json",
      "update":        "Update packages to their latest allowed version",
      "run":           "Run a script defined in package.json scripts section",
      "start":         "Run the start script (default: node server.js)",
      "test":          "Run the test script",
      "build":         "Run the build script",
      "publish":       "Publish a package to the npm registry",
      "init":          "Create a new package.json interactively",
      "audit":         "Scan dependencies for known vulnerabilities",
      "audit fix":     "Automatically fix audit vulnerabilities",
      "list":          "List installed packages",
      "ls":            "Alias for list",
      "outdated":      "Check which packages are outdated",
      "ci":            "Clean install from package-lock.json (for CI/CD)",
      "link":          "Symlink a local package for development",
      "pack":          "Create a tarball of the package",
      "version":       "Bump the package version",
      "cache clean":   "Delete cached package data",
      "--save":        "Save to dependencies in package.json (default in npm 5+)",
      "--save-dev":    "Save to devDependencies in package.json",
      "-D":            "Short for --save-dev",
      "--save-optional":"Save to optionalDependencies",
      "--global":      "Install package globally (system-wide)",
      "-g":            "Short for --global",
      "--production":  "Install only production dependencies (not devDependencies)",
      "--legacy-peer-deps":"Bypass peer dependency conflicts (npm 7+)",
      "--force":       "Force install, ignoring cache",
      "--prefix":      "Set install directory prefix",
      "--registry":    "Use a specific registry URL"
    }
  },

  // ── SYSTEMCTL ────────────────────────────────────────────────────────────
  systemctl: {
    tool: "systemctl",
    description: "Control the systemd system and service manager",
    args: { description: "Subcommand followed by unit name (e.g., start nginx)" },
    flags: {
      "start":          "Start (activate) one or more units",
      "stop":           "Stop (deactivate) one or more units",
      "restart":        "Stop and then start one or more units",
      "reload":         "Reload the unit configuration without stopping it",
      "reload-or-restart":"Reload if supported, otherwise restart",
      "enable":         "Enable a unit to start at boot",
      "disable":        "Disable a unit from starting at boot",
      "is-enabled":     "Check if a unit is enabled",
      "is-active":      "Check if a unit is currently active",
      "status":         "Show runtime status and recent logs of a unit",
      "show":           "Show properties of a unit in machine-readable form",
      "list-units":     "List loaded units (active, failed, etc.)",
      "list-unit-files":"List all installed unit files",
      "daemon-reload":  "Reload systemd manager configuration after editing unit files",
      "mask":           "Mask a unit (prevent it from being started at all)",
      "unmask":         "Unmask a unit",
      "cat":            "Show the unit file and drop-in overrides",
      "edit":           "Edit a unit file's drop-in override",
      "kill":           "Send a signal to a unit's processes",
      "reset-failed":   "Reset the failed state of all (or specified) units",
      "poweroff":       "Power off the system",
      "reboot":         "Reboot the system",
      "suspend":        "Suspend the system",
      "--now":          "Combine enable/disable with immediate start/stop",
      "--user":         "Operate on the user session's service manager",
      "--system":       "Operate on the system service manager (default)",
      "--failed":       "List only failed units",
      "--all":          "Show all units, including inactive",
      "--no-pager":     "Do not pipe output to a pager",
      "-l":             "Show full log lines without truncation"
    }
  },

  // ── JQ ───────────────────────────────────────────────────────────────────
  jq: {
    tool: "jq",
    description: "Lightweight command-line JSON processor",
    args: { description: "JQ filter expression followed by JSON file or piped input" },
    flags: {
      ".":             "Identity filter — output the input unchanged",
      ".field":        "Extract value of a named object field",
      ".[]":           "Iterate over all values in an array or object",
      ".[0]":          "Extract element at index 0 of an array",
      ".[2:5]":        "Array slice from index 2 to 4",
      "| ":            "Pipe: pass output of left filter to right filter",
      ",":             "Produce multiple outputs from one input",
      "select(expr)":  "Pass through values for which the expression is true",
      "map(expr)":     "Apply a filter to each element of an array",
      "keys":          "Return the keys of an object as a sorted array",
      "values":        "Return the values of an object as an array",
      "has(key)":      "Return true if the object has the given key",
      "in":            "Test if a value is a key in an object",
      "length":        "Return the length of an array, string, or object",
      "type":          "Return the type of a value (string, number, array…)",
      "empty":         "Produce no output (useful in conditionals)",
      "not":           "Logical negation of a boolean filter",
      "to_entries":    "Convert an object to an array of {key, value} pairs",
      "from_entries":  "Convert an array of {key, value} pairs to an object",
      "with_entries":  "Shorthand for to_entries | map(…) | from_entries",
      "add":           "Sum an array of numbers, or concatenate strings/arrays",
      "any":           "Return true if any element satisfies the condition",
      "all":           "Return true if all elements satisfy the condition",
      "group_by":      "Group array elements by a field value",
      "sort_by":       "Sort array elements by a field value",
      "unique_by":     "Remove duplicates by a field value",
      "first":         "Return the first output of an expression",
      "last":          "Return the last output of an expression",
      "limit(n;expr)": "Return at most n outputs from the expression",
      "env":           "Return the environment variables as a JSON object",
      "-r":            "Raw output — print strings without JSON quoting",
      "-c":            "Compact output — one JSON object per line",
      "-n":            "Null input — do not read input, use 'null' as input",
      "-e":            "Exit with non-zero status if the output is false/null",
      "-s":            "Slurp — read all input into a single array",
      "--arg":         "Pass a shell variable as a named jq string variable",
      "--argjson":     "Pass a shell value as a named jq JSON variable",
      "--slurpfile":   "Read a file and bind its contents as a jq variable",
      "--tab":         "Indent output using tabs instead of spaces",
      "--indent n":    "Use n spaces for indentation (1-7)"
    }
  },

  // ── OPENSSL ──────────────────────────────────────────────────────────────
  openssl: {
    tool: "openssl",
    description: "OpenSSL — cryptography toolkit and TLS/SSL library CLI",
    args: { description: "OpenSSL subcommand (genrsa, req, x509, s_client, enc, etc.)" },
    flags: {
      "genrsa":       "Generate an RSA private key",
      "genpkey":      "Generate a private key (supports RSA, EC, Ed25519)",
      "req":          "Create a certificate signing request (CSR) or self-signed cert",
      "x509":         "Display/sign/verify X.509 certificates",
      "pkcs12":       "Manage PKCS#12 bundles (.pfx / .p12)",
      "s_client":     "Connect to a TLS/SSL server (like curl for TLS debugging)",
      "s_server":     "Run a simple TLS/SSL test server",
      "enc":          "Encrypt or decrypt a file using a symmetric cipher",
      "dgst":         "Compute hash digests (MD5, SHA-256, SHA-512, etc.)",
      "verify":       "Verify a certificate chain",
      "crl":          "Manage Certificate Revocation Lists",
      "ca":           "Create and sign certificates as a CA",
      "rand":         "Generate random bytes",
      "speed":        "Benchmark cryptographic algorithms",
      "version":      "Display OpenSSL version information",
      "-newkey":      "Generate a new private key of the specified type/size",
      "-new":         "Create a new CSR",
      "-x509":        "Output a self-signed certificate instead of a CSR",
      "-key":         "Specify the private key file",
      "-in":          "Input filename",
      "-out":         "Output filename",
      "-days":        "Certificate validity period in days",
      "-subj":        "Subject name in one line (avoids interactive prompts)",
      "-nodes":       "Do not encrypt the private key (no DES)",
      "-noout":       "Do not output the encoded certificate or key",
      "-text":        "Print the certificate in human-readable text form",
      "-sha256":      "Use SHA-256 digest",
      "-sha512":      "Use SHA-512 digest",
      "-connect":     "Specify host:port for s_client",
      "-verify":      "Verification depth for certificate chain",
      "-CAfile":      "Trusted CA certificate file",
      "-servername":  "Set SNI hostname for TLS connection",
      "-passin":      "Input file passphrase source",
      "-passout":     "Output file passphrase source",
      "rsa:4096":     "RSA key with 4096-bit modulus",
      "rsa:2048":     "RSA key with 2048-bit modulus"
    }
  },

  // ── DOCKER COMPOSE ───────────────────────────────────────────────────────
  "docker-compose": {
    tool: "docker",
    description: "Define and run multi-container Docker apps (Compose v1 CLI)",
    args: { description: "Compose subcommand (up, down, build, logs, exec, etc.)" },
    flags: {
      "up":           "Create and start containers defined in docker-compose.yml",
      "down":         "Stop and remove containers, networks, and volumes",
      "build":        "Build or rebuild service images",
      "start":        "Start existing stopped containers",
      "stop":         "Stop running containers without removing them",
      "restart":      "Restart one or more services",
      "ps":           "List containers managed by Compose",
      "logs":         "View output from containers",
      "exec":         "Run a command inside a running service container",
      "run":          "Run a one-off command on a service",
      "pull":         "Pull service images from their registries",
      "push":         "Push service images to their registries",
      "config":       "Validate and view the merged Compose configuration",
      "rm":           "Remove stopped service containers",
      "scale":        "Set the number of containers for a service",
      "kill":         "Force stop service containers with a signal",
      "-d":           "Detached mode: run containers in background",
      "-f":           "Specify an alternate compose file",
      "--build":      "Build images before starting containers",
      "--force-recreate":"Recreate containers even if config hasn't changed",
      "--no-deps":    "Don't start linked services",
      "--volumes":    "Remove named volumes declared in Compose file (with down)",
      "--remove-orphans":"Remove containers for services not in the Compose file",
      "--tail":       "Number of log lines to show from the end",
      "--follow":     "Follow log output (like tail -f)",
      "--no-build":   "Don't build images, even if they're missing",
      "--abort-on-container-exit":"Stop all containers if any container stops"
    }
  },

  // ── AWS CLI ──────────────────────────────────────────────────────────────
  aws: {
    tool: "aws",
    description: "Amazon Web Services command-line interface",
    args: { description: "Service and subcommand (e.g., aws s3 ls, aws ec2 describe-instances)" },
    flags: {
      // Core services
      "s3":              "S3 object storage commands (ls, cp, mv, rm, sync, mb, rb)",
      "ec2":             "Elastic Compute Cloud — manage instances, AMIs, security groups",
      "iam":             "Identity and Access Management — users, roles, policies",
      "ecs":             "Elastic Container Service — run Docker containers at scale",
      "eks":             "Elastic Kubernetes Service — managed Kubernetes clusters",
      "ecr":             "Elastic Container Registry — private Docker image registry",
      "lambda":          "Run serverless functions",
      "cloudformation":  "Infrastructure as Code — stack create/update/delete",
      "rds":             "Relational Database Service — managed databases",
      "dynamodb":        "Managed NoSQL key-value and document database",
      "sts":             "Security Token Service — assume roles, get caller identity",
      "secretsmanager":  "Store and retrieve application secrets",
      "ssm":             "Systems Manager — parameter store, session manager",
      "logs":            "CloudWatch Logs — log groups, streams, insights",
      "cloudwatch":      "Metrics, alarms, and dashboards",
      "route53":         "DNS and domain management",
      "elb":             "Elastic Load Balancing",
      "vpc":             "Virtual Private Cloud networking",
      "elbv2":           "Application and Network Load Balancers",
      "configure":       "Set up AWS credentials and default region/output",
      // Common s3 subcommands
      "ls":              "List S3 buckets or objects",
      "cp":              "Copy files to/from S3",
      "mv":              "Move files to/from S3",
      "rm":              "Remove S3 objects",
      "sync":            "Sync a directory to/from S3",
      "mb":              "Create a new S3 bucket",
      "rb":              "Delete an S3 bucket",
      // Global flags
      "--profile":       "Use a named profile from ~/.aws/credentials",
      "--region":        "Override the default AWS region",
      "--output":        "Output format: json, yaml, text, table",
      "--query":         "JMESPath query to filter the output",
      "--endpoint-url":  "Override the service endpoint URL (useful for LocalStack)",
      "--no-verify-ssl": "Disable SSL certificate verification",
      "--dry-run":       "Check permissions without making changes",
      "--debug":         "Show detailed debug output and HTTP calls",
      "--no-paginate":   "Disable automatic pagination of results",
      "--color":         "Toggle colorized output: on, off, auto",
      "--cli-input-json":"Read parameters from a JSON file"
    }
  },

  // ── AZURE CLI ────────────────────────────────────────────────────────────
  az: {
    tool: "azure",
    description: "Microsoft Azure command-line interface",
    args: { description: "Service group and command (e.g., az vm list, az group create)" },
    flags: {
      // Core service groups
      "login":           "Authenticate to Azure (browser or service principal)",
      "logout":          "Log out from Azure",
      "account":         "Manage Azure subscriptions and tenants",
      "group":           "Manage resource groups",
      "vm":              "Manage Azure Virtual Machines",
      "storage":         "Manage storage accounts, blobs, queues, and tables",
      "network":         "Manage virtual networks, subnets, NICs, and NSGs",
      "aks":             "Manage Azure Kubernetes Service clusters",
      "acr":             "Manage Azure Container Registry",
      "webapp":          "Manage Azure App Service web apps",
      "functionapp":     "Manage Azure Function Apps",
      "keyvault":        "Manage Azure Key Vault secrets, keys, and certificates",
      "ad":              "Manage Azure Active Directory entities",
      "role":            "Manage role-based access control (RBAC)",
      "policy":          "Manage Azure Policy assignments and definitions",
      "monitor":         "Manage metrics, alerts, logs, and diagnostics",
      "devops":          "Manage Azure DevOps pipelines and repos",
      "sql":             "Manage Azure SQL databases",
      "cosmosdb":        "Manage Azure Cosmos DB accounts",
      "redis":           "Manage Azure Cache for Redis",
      "servicebus":      "Manage Azure Service Bus namespaces and queues",
      "configure":       "Configure az CLI defaults (location, group, etc.)",
      // Common subcommands
      "list":            "List resources of a given type",
      "show":            "Show details of a specific resource",
      "create":          "Create a new resource",
      "delete":          "Delete a resource",
      "update":          "Update properties of a resource",
      "start":           "Start a VM or other stoppable resource",
      "stop":            "Stop (deallocate) a VM",
      "restart":         "Restart a VM or web app",
      "get-credentials": "Download kubeconfig for an AKS cluster",
      // Global flags
      "--resource-group": "Resource group name",
      "-g":               "Short for --resource-group",
      "--name":           "Resource name",
      "-n":               "Short for --name",
      "--location":       "Azure region (e.g., eastus, westeurope)",
      "-l":               "Short for --location",
      "--subscription":   "Subscription name or ID to use",
      "--output":         "Output format: json, jsonc, yaml, table, tsv, none",
      "-o":               "Short for --output",
      "--query":          "JMESPath query string to filter output",
      "--yes":            "Do not prompt for confirmation",
      "-y":               "Short for --yes",
      "--no-wait":        "Do not wait for long-running operations to finish",
      "--debug":          "Show detailed debug and HTTP request logs",
      "--verbose":        "Show verbose logging",
      "--only-show-errors":"Only show errors (suppress warnings)"
    }
  },

  // ── GCLOUD ───────────────────────────────────────────────────────────────
  gcloud: {
    tool: "gcloud",
    description: "Google Cloud SDK command-line interface",
    args: { description: "Service group and command (e.g., gcloud compute instances list)" },
    flags: {
      // Core service groups
      "init":            "Initialise gcloud config — set account, project, region",
      "auth":            "Manage authentication credentials and service accounts",
      "config":          "View and set gcloud configuration properties",
      "compute":         "Manage Google Compute Engine VMs, disks, and networks",
      "container":       "Manage Google Kubernetes Engine (GKE) clusters",
      "storage":         "Manage Google Cloud Storage buckets and objects (gsutil successor)",
      "functions":       "Manage Google Cloud Functions (serverless)",
      "run":             "Deploy and manage Cloud Run services (serverless containers)",
      "sql":             "Manage Cloud SQL database instances",
      "iam":             "Manage IAM policies, roles, and service accounts",
      "projects":        "List, create, and manage GCP projects",
      "services":        "Enable, disable, and list GCP APIs and services",
      "pubsub":          "Manage Pub/Sub topics and subscriptions",
      "logging":         "Read and manage Cloud Logging log entries",
      "monitoring":      "Manage Cloud Monitoring dashboards and alert policies",
      "builds":          "Submit and manage Cloud Build jobs",
      "artifacts":       "Manage Artifact Registry repositories and packages",
      "secrets":         "Manage Secret Manager secrets",
      "dns":             "Manage Cloud DNS zones and records",
      // auth subcommands
      "login":           "Authenticate with a Google account via browser",
      "activate-service-account": "Authenticate using a service account key file",
      "list":            "List credentialed accounts",
      "application-default": "Manage Application Default Credentials (ADC)",
      // compute subcommands
      "instances":       "Manage Compute Engine VM instances",
      "disks":           "Manage persistent disks",
      "images":          "Manage VM images",
      "ssh":             "SSH into a Compute Engine instance",
      "scp":             "Copy files to/from a Compute Engine instance",
      // container subcommands
      "clusters":        "Manage GKE clusters",
      "get-credentials": "Fetch kubeconfig credentials for a GKE cluster",
      // Global flags
      "--project":       "GCP project ID to use",
      "--region":        "Compute region (e.g., us-central1)",
      "--zone":          "Compute zone (e.g., us-central1-a)",
      "--account":       "Google account or service account to use",
      "--format":        "Output format: json, yaml, table, csv, text, none",
      "--quiet":         "Suppress interactive prompts",
      "-q":              "Short for --quiet",
      "--verbosity":     "Logging verbosity: debug, info, warning, error, critical, none",
      "--configuration": "Named gcloud config to use",
      "--impersonate-service-account": "Run as a service account (requires iam.serviceAccountTokenCreator)",
      "--no-user-output-enabled": "Suppress all user output",
      "--log-http":      "Log all HTTP requests and responses (for debugging)"
    }
  }
};

// Merge extra commands into the main COMMANDS object
// (Called after both commands.js and this file are loaded)
function mergeExtraCommands() {
  Object.assign(COMMANDS, EXTRA_COMMANDS);
  // Tag all unix commands
  const unixCmds = [
    "ls","grep","find","chmod","tar","curl","ssh","awk","sed",
    "ps","kill","cp","mv","rm","mkdir","cat","echo","ping","netstat","df","du",
    "top","head","tail","wc","sort","uniq","xargs","chown","ln","cron",
    "crontab","wget","rsync","scp","tee","cut","tr","date","uname","which",
    "env","export","free","lsof","ss","watch","dig","ip","zip","unzip",
    "vim","nano","htop","journalctl"
  ];
  unixCmds.forEach(k => { if (COMMANDS[k] && !COMMANDS[k].tool) COMMANDS[k].tool = "unix"; });
  if (COMMANDS["docker"]) COMMANDS["docker"].tool = "docker";
  if (COMMANDS["aws"])    COMMANDS["aws"].tool    = "aws";
  if (COMMANDS["az"])     COMMANDS["az"].tool     = "azure";
  if (COMMANDS["gcloud"]) COMMANDS["gcloud"].tool = "gcloud";
}
